### ISSUE TITLE
Adjacent rooms

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/TEASER#117]
Allow the definition of multiple exterior walls that are connected to multiple adjacent rooms with defined temperature, preferably as profile. This would force changes of `EqAirTemp` Model in AixLib as well to allow adjacent rooms (one vector with weightfactors and one with temperatures or connector to profiles).

**Comment by InaDJ** [comment]
@mlauster
Hi Moritz, 
I have been using TEASER to translate CityGML files into IDEAS models (I told you I was planning to do that when we were in Corsica). Now, I do have a problem and I would like to hear your view on this. Within the CityGML files, all buildings are represented by all of their wall surfaces (shared walls are thus two overlapping surfaces). Treating these shared walls as external walls means a significant overestimation of the energy use of a terraced house or even a semi-detached house. I am aware of your solution for residential buildings, but this does not apply when importing a CityGML file, right? Therefore, I implemented in TEASER the possibility to "detect" shared walls and delete them. Is this something you plan to include in TEASER? 
My approach seemed to work well, until I tried it to apply it to a more detailed CityGML model and then it didn't detect all shared walls anymore. I'll explain my approach in short: if you import a CityGML file in TEASER, TEASER takes every surface and creates either a Wall, Roof or Groundfloor for it. After these are all created, I loop all these surfaces again, looking for an overlapping surface (I did this by determining the "equation" of the surface, based on the normal vector and one point). If there is an overlapping surface, I calculate their common area (using another Python package (Shapely, I think)) and subtract it from the original area. This is equal to just deleting the overlapping part (by which you also lose its thermal mass). In case the resulting area is zero, I just delete the Wall-object. But as I said, this approach does not work yet in all cases (I think that my surfaces are really overlapping in CityGML, so probably it is due to rounding errors while determining the equation of the surface (issue of the floating point error!)). 
I think detecting these shared walls would be an enhancement for TEASER, but the user should be able to choose if he'd like to detect these or not, as it could increase the calculation time (scanning 100 buildings for adjacant surfaces took about a minute or two tops in my case, if I remember correctly). Instead of deleting them, we could "label" them as internal walls or create a new type of walls?
In case you are not planning to include this in TEASER, I won't look for a solution to my problem any further and try to just delete the shared walls before creating my CityGML models and then importing these improved ones into TEASER. 
Looking forward to hear your opinion on this, 
Kind regards, 
Ina

**Comment by mlauster** [comment]
@InaDJ, sounds like great work so far! As mentioned by @PRemmen in #440, we are really looking forward to get more people working on TEASER and are happy about all new features and improvements. So go ahead, we can discuss your topics in more detail within PRs that allow reviewing the code. Regarding your problem mentioned here, it would be great if you can track down the problems (is it indeed a rounding problem?) and then we could discuss what possible solutions are. In general, having a functionality to identify and change/delete adjacent walls is really a huge advancement. At our institute, we have some additional tools that plan to go open-source and to integrate CityGML import. On the long run, we think about having a stand-alone open-source Python-package for CityGML import that can be seamlessly coupled to TEASER or even other tools. For this, your functionality would even have a bigger impact.

**Comment by mlauster** [comment]
@InaDJ, is there any progress on that? Do you still plan to integrate your modules? Would still be very great! :)

**Comment by InaDJ** [comment]
@mlauster, yes, I have been working on it, I'm sorry I haven't reported on it. So, my code detects walls that are exactly coplanar. There are currently 2 problems with it: firstly, it loops over all of the wall surfaces that are included in the entire project. This might be time-consuming for larger neighbourhoods. Maybe we could integrate something like a bounding box around the wall for which we are looking for adjacant surfaces and then only consider possible adjacant surfaces within the bounding box. Secondly, I tried to set like an allowable deviation on the coplanarity of the walls, but that did not work out. In my CityGML models, there are some errors on the geometry (so neighbour buildings are 10 cm apart in the model, of course this is an error). I wanted to allow a deviation of about 10 cm on the surfaces, but this is not as straightforward as it might seem. But anyways, I'll try to push my current version this week.

**Comment by mlauster** [comment]
Thanks, @InaDJ for that update! We are happy to add your current version as a branch and discuss the further process to get a stable version! Detecting adjacent surfaces is a tricky thing and we should start with a first working version that might have its drawbacks.

**Comment by mlauster** [comment]
There is currently no work planned on this, please reopen if somebody takes over the work.
