### ISSUE TITLE
new attribute user_id for building

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/TEASER#269]
To create buildings out of data from a database, let them simulate, load the results and combine these results with the initial data, I need a unique identifier that stays constant throughout the entire process. In Modelica, we have an attribute `buildingID`, I would like to add this to teaser as `user_id` on building level. Is this okay or any objections?

**Comment by PRemmen** [comment]
no objections.

**Comment by MichaMans** [comment]
Every building in TEASER has a unique id. Could you use this as an indentifier?

**Comment by mlauster** [comment]
No, I need to set this identifier to a specific value (e.g. the building number or the id given in the database). After the simulation, I can use this identifier to retrieve the original entry in the database.

**Comment by MichaMans** [comment]
Yes, but isn't that possible? Can't you create a building and then call bldg.internal_id = yourpersonalvalue? Would that help? we are using this attritbute only for the gui (atm), aren't we?

**Comment by mlauster** [comment]
If the system doesn't crash in case I change this ID if necessary. Is it a string?

**Comment by MichaMans** [comment]
Mh i think this is possible, we are currently using this to link the buildings shown in the gui, to the buildings in the logic. So if you are not using the gui, it should work. I would prefer this way in a first guess, because this attribute provides the same functionality you asked for, without implementing a new attribute.

**Comment by mlauster** [comment]
And when using the GUI? I just mean, does it makes sense to implement something that doesn't work with all other features in an acceptable way?

**Comment by MichaMans** [comment]
I'm not sure if i understood you right. But isn't it a point of view here? If we need to implement a unique indentifier for our buildings in the TEASER building class, i don't disagree with you, the only thing i'm trying to say is, that we already have a unique identifier. So why we don't use this one? In our case we need this to link the gui with the logic, in your case you need it to link the database with the TEASER logic, for me this is pretty much the same use of this attribute. What you don't do (for now) is that you are using this attribute with the gui and the database at the same time, since this is not implemented in the gui.

**Comment by mlauster** [comment]
Okay, but it would be possible and not too cumbersome to use it in the gui and as a continuous identifier in the process? I can change this identifier (having the gui running in the worst case) without crashing TEASER? There are no limitations how the identifier is defined (length, characters)? TEASER does not change the identifier by itself (what would mean I loose my connection to the other process parts)? Then I'm fine with using the existing one. :)
