### ISSUE TITLE
integrate heating/cooling times in export for AixLib

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/TEASER#278]
Currently the ideal Heater Cooler in AixLib is always turned on. We should integrate the possibility to use the heating and cooling times given in 18599. We need to adjust our export

The heaterCooler in Multizone needs to be changed (statOrDyn set to Dynamic) and a BooleanTable needs to be connected.

@MichaMans @mlauster Should we give additional parameter to export function or should the heating and cooling times from 18599 should be set as default?

**Comment by mlauster** [comment]
Yes, we could add this functionality. I think there was a reason why I decided so stick to a static behavior (always on or off), related to conditional sub-models and connectors in `HeaterCoolerPI` that would make it hard to set up a vectorized model (due to the unknown structure of the connector vectors). But we withdraw that conditions, so it should be easy to do with the current model.

**Comment by PRemmen** [comment]
This is implicitly solved by integrating night set back for temperatures, in addition the documentation states clearly that these parameters are not used
