### ISSUE TITLE
Support of full-scale CityGML files

### ISSUE THREAD

**Issue by mlauster** [RWTH-EBC/TEASER#331]
At the gensim workshop, one participant tried to load an example file from the cityGML homepage (we could open it with FZK Viewer, so it seems to be valid), TEASER crashed due to some binding issues. We suspected that TEASER couldn't handle unknown objects defined in the file.

**Comment by PRemmen** [comment]
- Without error messages it's not possible to tell why it crashes. CityGML allows a lot of different ways to define objects (e.g. surfaces of buildings) even in the same LoD. TEASER is only capable of interpreting some of them.
- not sure what you mean by a"full-scale" citygml file. However, teaser comes only with some namespaces of citygml that are really needed for model generation (mainly issue because of file size) if you want to use all namespaces you can use full bindings of pyxb (https://github.com/pabigot/pyxb/tree/next/pyxb/bundles/opengis/scripts), pleayse remember to use pyxb version 1.2.4 while creating the bindings. 
- another solution would be to add the bindings to this repository.

**Comment by mlauster** [comment]
It was an example for waldbruecke  (or something similar) from the citygml Website . I have the File but currently Not the bandwith to upload them . The error message was some unknown namespace, objects in pyxb or so. I'm as well Not yet sure how to handle that best. to create the bindings , users would need to have Linux (if I remember correctly), supporting all objects really seems to blow up Teaser quite unneccessarily. maybe we could provide an example File with all objects supported by Teaser and add some information to this to documentation.



Von meinem Samsung Gerät gesendet.


-------- Ursprüngliche Nachricht --------
Von: Peter Remmen <notifications@github.com>
Datum: 28.10.2016 08:47 (GMT+01:00)
An: RWTH-EBC/TEASER <TEASER@noreply.github.com>
Cc: "Lauster, Moritz" <MLauster@eonerc.rwth-aachen.de>, Author <author@noreply.github.com>
Betreff: Re: [RWTH-EBC/TEASER] Support of full-scale CityGML files (#331)


  *   Without error messages it's not possible to tell why it crashes. CityGML allows a lot of different ways to define objects (e.g. surfaces of buildings) even in the same LoD. TEASER is only capable of interpreting some of them.
  *   not sure what you mean by a"full-scale" citygml file. However, teaser comes only with some namespaces of citygml that are really needed for model generation (mainly issue because of file size) if you want to use all namespaces you can use full bindings of pyxb (https://github.com/pabigot/pyxb/tree/next/pyxb/bundles/opengis/scripts), pleayse remember to use pyxb version 1.2.4 while creating the bindings.
  *   another solution would be to add the bindings to this repository.

**Comment by mlauster** [comment]
This issue is also on hold as long as we get no further complaints about loading data to Teaser. The reason is that there is no good solution so far, adding all bindings would lead to a lot of overhead just for one specific application
