### ISSUE TITLE
Cooling in example office building

### ISSUE THREAD

**Issue by FelixBue** [RWTH-EBC/TEASER#376]
Hi, I noticed that there is no cooling load in the office building (type_bldg_office). Marcus told me that there is no AHU used in this type and I should open an issue here in order to discuss whether there should be one or not.

**Comment by mlauster** [comment]
hey Felix!

We currently use an office building definition according to a BMVBS definition, resp. from a Disseration of Markus Lichtmess. This definition does not include any AHU. AS an alternative, you could implement an alternative version as "custom" archetype inculding AHU. To push that into the master, we would need a clear definition and at best references you build your custom office building on.

Am 10.01.2017 um 18:56 schrieb Felix Bünning <notifications@github.com<mailto:notifications@github.com>>:


Hi, I noticed that there is no cooling load in the office building (type_bldg_office). Marcus told me that there is no AHU used in this type and I should open an issue here in order to discuss whether there should be one or not.

**Comment by MichaMans** [comment]
I would agree with @mlauster with the addition that we could / should think about making the coolerOn attribute of each zone available in TEASER. This would provide a method for the user to calculate ideal cooling demand for specific zones and we must not use the AHU with all the real air conditioning.

**Comment by FelixBue** [comment]
I have solved my problem by just activating the cooler in the Modelica records after the export, which was a bit easier for me than trying to figure out how exactly it is implemented in TEASER.

I do however agree with @MichaMans that it would be nice if this could be chosen by the user directly in TEASER.

**Comment by PRemmen** [comment]
We can reopen an issue adressing clearly the proposal of @MichaMans
