### ISSUE TITLE
Replace IBPSA with individual libraries

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/TEASER#440]
### What is our Problem?

- Currently we support the export for ROM for IBPSA library
- As suggested in https://github.com/ibpsa/modelica/issues/700 we should support model export for the individual libraries (https://github.com/UdK-VPT/BuildingSystems, https://github.com/open-ideas/IDEAS, https://github.com/lbl-srg/modelica-buildings and of course https://github.com/RWTH-EBC/AixLib) as not IBPSA library should be used but one of these

### Why do we want to solve it?

- to enhance model export and make teaser more attractive to users from other libraries

### How do we want to solve it?

- in Project.py function `export_ibpsa` we could add a parameters that needs to be either `Buildings`, `BuildingSystems`, `IDEAS` or `AixLib` this string will be passed to the templates
- in the templates we add placeholders for each library name as the structure in each library should be the same
- also add names of the libraries in the documentation

**Comment by InaDJ** [comment]
@PRemmen, I wanted to use TEASER in combination with IDEAS (I'm a researcher at KULeuven - Building Physics and I wanted to make some simulations using detailed IDEAS building models and not ROM). Therefore, I implemented the possibility to export to IDEAS. I made templates for these detailed models (also using the MAKO template engine) and mapped the TEASER variables immediately to the ones in IDEAS without making use of the R-C-calculations. I am wondering what your general view is on this subject? Will there be the possibility to export to non-reduced-order-models? Or will it remain only ROM but in different libraries? In case you'd like to see how I tackled it, I can always share my code. (I really like using TEASER because it is easy in use and easy to adapt to my personal needs, so thank you for making it open-source, I'll share my other thoughts for enhancements in the corresponding issues).

**Comment by PRemmen** [comment]
@InaDJ great to hear from you!! We would very much like to see and implement your input (also from #117 ). So I propose you make two Pull Request (for  and #117 #440) against our development branch and we will review code :)

**Comment by InaDJ** [comment]
@PRemmen @mlauster I'm sorry that it has been a while, I have been working on my IDEAS export models, but I think I need to improve my code first. I want to enable multiple export options, so I'll push it in the future, but I can't yet say when a more or less final version will be ready. Sorry! I hope that's okay for you!
