### ISSUE TITLE
Number of occupants for residential archetypes is not correct

### ISSUE THREAD

**Issue by SebastianStinner** [RWTH-EBC/TEASER#480]
## What is the problem?

- If generating an archetype dataset for residential buildings, the number of occupants is always set to 1.5 and not scaled according to the area of the building.

## Why do we want to solve it?

- Because it would be good to have some estimated data for occupancy directly available in the archetype record.

**Comment by MichaMans** [comment]
Do you have a suggestion how we should solve this? At the moment the documentation is a bit fuzzy regarding the number of people etc. The number of people are defined in the SIA as 1.5 W/m². So it is a scalable value, but we are not using it that way because we are exporting the 1.5 as number of persons. What are your thoughts about that? Should we use the scalable value and recalculate at the point of the export how many people that should be?

**Comment by PRemmen** [comment]
this is now solved in #523 and #524
