### ISSUE TITLE
Heizlastausschläge im Sommer

### ISSUE THREAD

**Issue by RWTHSebastian** [RWTH-EBC/TEASER#497]
![sommerheizlastspitzen](https://user-images.githubusercontent.com/19650702/33832807-bef4828e-de7d-11e7-9002-711f53e9a47e.PNG)

## What is the problem?

- In den Sommermonaten treten große Heizlastausschläge auf (siehe Bild, EFH 1968). Das würde ja heißen, dass im Sommer nachts die Heizung angeschaltet werden müsste. Dabei ist es doch so, dass gerade im Sommer die kalten Nächte genutzt werden, um das Gebäude zu kühlen. Sprich man würde es unter allen Umständen vermeiden zu heizen.

## Why do we want to solve it?

- Für das Projekt GeTIS benutzen wir die Heizlastkurven von TEASER und binden diese an geothermische Modelle an. Die Heizlasten im Sommer machen für mich keinen Sinn und wirken sich negativ auf die Anlageneffizienz und das Regenerationsverhalten im Boden aus.

## How do we want to solve it?

- Wäre es sinnvoll in den Sommermonaten die Heizlasten auf Null zu setzten? Eventuell auch in Abhängigkeit der aktuellen Außentemperatur oder der Außentemperaturen der letzten 24 oder 48 h?

**Comment by PRemmen** [comment]
@RWTHSebastian Thanks for raising this issue!

First of all: I would like you to ask if you could change your issue into english language. This helps other users to follow our discussion. www.deepl.com might be a fast an easy way to do this.

The models, TEASER generates, have no detailed control logic. Currently it is a simple set point temperature that is provided in the class Use Conditions. In addition a night set back is implemented, that lowers the set-point temperature to a certain values. If the room temerpature falls below those temperatures (which may also occur in summer) a heating load will be simulated.

Our current approach is to try to limit the control inputs in the Reduced-Order-Model as much as possible, because every use case is different (e.g. heating periods may not always be the same among different projects). TEASER enables you to change the mentioned parameters (set-temperature, night-setback) already. If you need a more sophisticated control, you may add an own set-temperature table to your model. If this still does not fit your needs I would suggest to open a new issue that directly describes the new feature you want to implement.

For now (andalso  because this issue is in german) I will close this.
