### ISSUE TITLE
Kühllast in TEASER

### ISSUE THREAD

**Issue by RWTHSebastian** [RWTH-EBC/TEASER#503]
Bisher ist die Berechnung der Kühllast in TEASER nicht möglich. P_cooler immer auf Null, auch bei großen non_residential Gebäuden.

**Wird die Kühllastberechnung bald in TEASER integriert?**

**Comment by MichaMans** [comment]
Thanks for rising this issue. If i understand you right, you want to calculate the cooling load in TEASER. At the current state this is not yet integrated. One reason is that we first need to integrate the full calculation core of the VDI 6007 where the cooling load calculation of the VDI 2078 is based on. 
If i didn't understood you right and you might want to simulate cooling loads with the modelica models within dymola for example, you might be able to set the right parameters within the exported modelica models. For an automated export we already have the issue #438 . Feel free to contribute and discuss in this issue. Since this is duplicate, I'll close this one.
P.S.: Sticking to English might help other readers to follow the conversation here
