### ISSUE TITLE
Calculation of VDI Room 1 S does not match the calculation from Rouvel

### ISSUE THREAD

**Issue by yfuerst** [RWTH-EBC/TEASER#549]
I am using teaser 0.6.4 from pip to validate my own implementation of the VDI 6007. The output of `examples/verification/verification_VDI_6007_room1.py` is

```
Parameters for inner wall
r1_iw: 0.0005956934075105781 K/W --- Rouvel: 0.000595515 K/W
c1_iw:  14836.354628150488 kJ/K --- Rouvel: 14836.2 kJ/K
area_iw:  75.5 m2 --- Rouvel: 75.5 m2
alpha_weight_conv_iw:  2.2364238410596027 W/(m2*K) --- Rouvel: 2.236423594 W/(m2*K)

Parameters for outer wall
r_rest_ow 0.031340147950013164 K/W --- Rouvel: 0.042768721 K/W
r1_ow: 0.004367912936735758 K/W --- Rouvel: 0.004367913 K/W
c1_ow:  1600.84893985435 kJ/K --- Rouvel: 1600.8 kJ/K
area_ow+area_win:  24.5 m2 --- Rouvel: 10.5 m2
alpha_conv_inner_ow:  2.7 W/(m2*K) --- Rouvel: 2.7 W/(qm*K)
alpha_comb_outer_ow:  25.0 W/(m2*K) --- Rouvel: 25.0 W/(m2*K)
```

The value `r_rest_ow` doesn't match the calculation from Rouvel. My own calculation does, so I am wondering whether this is an error in teaser or a modification from your side.

On the other hand I found a small mistake: you are calculating `area_ow*area_win` instead of `area_ow+area_win`

**Comment by mlauster** [comment]
@yfuerst, thanks for digging that out and using TEASER for benchmark!
Regarding your questions:
1. That's a modification inside TEASER. The VDI combines heat transfer through the passive part of the wall (the remaining or "Rest" part) and outside heat transfer due to convection and radiation. As this is handled separately on the inside part of the wall (by two resistances, one for heat transfer within the wall and one for the heat exchange), we decided for reasons of clarity, to also distinguish this on the outside. In consequence, `r_rest_ow` + 1/(`alpha_comb_outer_ow`*`area_ow`) = 0.042768
2. You are right, that's a bug in the script, I will fix that!

One question in return: Why are you implementing your own version of VDI 6007-1 instead of using the parts of TEASER, that fullfill your needs? Is there something missing? We would be happy to combine our works and have you on board of the TEASER development!

**Comment by yfuerst** [comment]
Thank you for the clarification.

I started working on my own implementation before I knew of TEASER. The only reason I am still sticking to it are personal habits: I know my code and I am not very familiar with the whole TEASER framework (I am only interested in the calculation of the model parameters). You are definitely right, working together makes sense. Especially since imho the documentation of the VDI 6007 is very poor.
