### ISSUE TITLE
Delete load_citygml

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/TEASER#582]
## What is the problem?

- if we want to lose dependency of pyxb then we need to delete the input

## Why do we want to solve it?

- we do not want to use pyxb anymore #508 

## How do we want to solve it?

- delete it
- in future we will publish ORM classes for 3DCityDB that will be able to import and export to teaser

**Comment by MichaMans** [comment]
Maybe we can also think about still supporting the load city gml function. This still provides some useful exchange format with a widely used schema.

**Comment by lamingblu** [comment]
Dear Team,

using the "load_gml_energy" since "load_citygml" does not exist anymore still causes the problem of an deprecated option. Me being relatively new to this, could you indicate a solution to my problem to import .gml files? To my understanding it is not mandatory for TEASER to use TEASER+ in order to import .gml-files right?

Btw: I am currently working on my Masterthesis during my work as a project engineer working in the public sector where I want to simulate and analyze the energetic retrofit of around 2000 buildings in the city of Duesseldorf. I am starting from the use of a commercial software for around 34 buildings a detailed building information over to the use of open-source-tools for the whole building stock. Looking into both the financial advantage of the use of open-source-tools as well as faster preparations for the political decision-making process of municipalities.  

I am happy for any help regarding my current problem to import of .gml files as well as any feedback about the general approach of my idea.


Thanks, Lamine
