### ISSUE TITLE
Integrate threshold temperatures for ideal heaters and coolers

### ISSUE THREAD

**Issue by DaJansenGit** [RWTH-EBC/TEASER#617]
This belongs to:
https://github.com/RWTH-EBC/AixLib/pull/732

**Comment by PRemmen** [comment]
@marcusfuchs just called me, it seems that although the variable "use_conditions._with_ideal_thresholds" is the to False, in the exported models it will always simulate with a certain threshold. This leads to much smaller cooling load then before and in addition to very high peak loads @DaJansenGit can you have a look at it? probably the error is in AixLib (e. g. variables are not passed to ideal heater)

**Comment by marcusfuchs** [comment]
@PRemmen Thanks for documenting this! From what I understand, it seems like the `multizone.zone[1].heaterCoolerController` model shuts off the heater and cooler even though `with_ideal_thresholds` is set to False. This caused our automated tests to fail, because the simulated demands for our test suite of buildings differ greatly from the reference values.

**Comment by DaJansenGit** [comment]
this was an AixLib problem and not a TEASER problem. We solved it and the fix will be implemented with https://github.com/RWTH-EBC/AixLib/pull/847

**Comment by marcusfuchs** [comment]
@DaJansenGit Thanks for all the work over the last days! With the merge of RWTH-EBC/AixLib#847 and #594, is this finished from your side? I noticed that after these merges, the versions of the development branches again do not match (see #622) - AixLib development is at v0.8.3 but models generated by TEASER development include a `uses` statement for v0.8.1 . If your work is finished, I could again bump the TEASER requirement in a new PR, otherwise I would wait before we fix this and run our test set again.

**Comment by DaJansenGit** [comment]
you are right, this will be solved with #626
