### ISSUE TITLE
Does it essential to purchase DYMOLA for using TEASER?

### ISSUE THREAD

**Issue by KaipengXu96** [RWTH-EBC/TEASER#693]
I’m a PhD student and I’m trying to use TEASER to generate some building models and used these models to test some control systems.
 
I wonder if it is essential to purchase DYMOLA to achieve above objectives, since DYMOLA always report errors when I trying to translate the models in “TEASER output” file, I suspect this is because of i'm using a free trial version of DYMOLA.

**Comment by MichaMans** [comment]
@KaipengXu96 If Dymola does not translate because the models or the system is too complex, then you need to purchase a license. Another possibility is to check how the compatibility of the used models is regarding the use of OpenModelica (At the moment the models are not supported I guess, but this needs to be clarified).
For further more general questions, feel free to contact via mail: ebc-teaser@eonerc.rwth-aachen.de
